export const api_root = 'https://vr-server.sparki.cn/api/'
export const url_root = 'https://vr-server.sparki.cn/'
export const upload_url = 'product'
export const max_upload_size_m = 20
export const max_upload_size = max_upload_size_m * 1024 * 1024
// export const api_root = 'http://vr.dev/api/'
// export const url_root = 'http://vr.dev/'
export const client_id = '2'
export const client_secret = 'Y1UNb8UmAbkV6YWfKGd69gJ5kdv9ptlEWkyW9Qba'
